---
fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.1'
    file_concat:
      repo: 'git://github.com/electrical/puppet-lib-file_concat.git'
      ref: '1.0.1'
  symlinks:
    stunnel: "#{source_dir}"
